### ISSUE TITLE
Error: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by mlava** [gleeds/cloudbbq#9]
Hi there,
Thanks for this repository. I hope to get it working soon.
I had a bunch of issues with npm install, but have gradually worked through the folder permissions issues I had and had a successful npm rebuild.
When I npm start I get the following error:

```
> cloudbbq@1.0.0 start /home/pi/cloudbbq
> node app.js

/home/pi/cloudbbq/node_modules/grpc/src/grpc_extension.js:58
    throw e;
    ^

Error: Failed to load /home/pi/cloudbbq/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc/grpc_node.node. /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/cloudbbq/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc/grpc_node.node)
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/cloudbbq/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

```

I've tried to do apt-get update, upgrade and dist-update etc but no luck.
I am not sure how to fix the CXX error.
Running on PiZeroW.

Any hints? :-)

**Comment by mlava** [comment]
@gleeds 
Just an FYI in case you've got your notifications turned off :)
